---
abstract: 'Xapian engine for OpenSearch results'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-OpenSearch-Engine-Xapian
no_index:
  directory:
    - t
    - inc
requires:
  SWISH::Prog: 0.54
  SWISH::Prog::Xapian: 0.08
  Search::OpenSearch: 0.15
  Test::More: 0
  perl: 5.008003
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-OpenSearch-Engine-Xapian
  homepage: https://github.com/karpet/search-opensearch-engine-xapian-perl
  license: http://dev.perl.org/licenses/
  repository: git://github.com/karpet/search-opensearch-engine-xapian-perl.git
version: 0.05
