--- #YAML:1.0
name:               Search-OpenSearch-Engine-Xapian
version:            0.03
abstract:           Xapian engine for OpenSearch results
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:                 5.008003
    Search::OpenSearch:   0.15
    SWISH::Prog:          0.54
    SWISH::Prog::Xapian:  0.08
    Test::More:           0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Search-OpenSearch-Engine-Xapian
    homepage:    https://github.com/karpet/search-opensearch-engine-xapian-perl
    license:     http://dev.perl.org/licenses/
    repository:  git://github.com/karpet/search-opensearch-engine-xapian-perl.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
